version: '3.8'
services:
  formik-for-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
