version: '3.8'
services:
  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    env_file:
      - .env

volumes:
  node_modules:
  build:
