name: Deploy Frontend

on:
  push:
    branches:
      - docker
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER || 'your-docker-username' }}
          password: ${{ secrets.DOCKER_PASSWORD || 'your-docker-password' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: sebastiankociuba/formik-for-backend:latest

  deploy:
      name: Deploy Frontend Container
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              set -e

              cd /var/www/frontend

              # Pobranie najnowszego obrazu
              sudo docker pull sebastiankociuba/formik-for-backend:latest

              # Zatrzymanie i usunięcie starego kontenera
              sudo docker stop nextjs-app || true
              sudo docker rm nextjs-app || true

              # Uruchomienie nowego kontenera
              sudo docker run -d --restart unless-stopped \
                -p 3000:3000 \
                --env NEXT_PUBLIC_API_URL=http://127.0.0.1:8000 \
                --env NODE_ENV=production \
                --name nextjs-app \
                sebastiankociuba/formik-for-backend:latest

